### ISSUE TITLE
issue with samply.py

### ISSUE THREAD

**Issue by haddadi** [sapmlresearch/DiffPrivate_FedLearning#9]
Hello
was wondering if anyone has faced this before? upon running a clean install I get:

python sample.py -N 100
/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "sample.py", line 86, in <module>
    help='Directory.'
  File "/anaconda2/lib/python2.7/argparse.py", line 1308, in add_argument
    return self._add_action(action)
  File "/anaconda2/lib/python2.7/argparse.py", line 1682, in _add_action
    self._optionals._add_action(action)
  File "/anaconda2/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/anaconda2/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/anaconda2/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/anaconda2/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --save_dir: conflicting option string(s): --save_dir

**Comment by cyrusgeyer** [comment]
I think the newest commit should fix the issue
